GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "Dill.Pickles@FreeRealestate.com",
  "password": "Dill.Pickles"
}

###

GET http://localhost:3000/api/showings/home/1234567/cklpo0u370031ygzey1efm7us/feedback
Content-Type: application/json

{
}

###

POST http://localhost:3000/api/showings/home/1234567
Content-Type: application/json

{
  "date": "2021-03-02T00:04:36.503Z",
  "confirmed": true
}

###

GET http://localhost:3000/api/showings/home/1234567
Content-Type: application/json

{
}

###

POST http://localhost:3000/api/showings/home/1234567/cklwywrpl004596zeiuz8a14d/feedback
Content-Type: application/json

{
  "isInterested": true,
  "experience": "VERY_GOOD",
  "priceOpinion": "VERY_GOOD",
  "notes": "KomodoHype PAUSERS"
}